name: Build and Deploy Pokémon Showdown

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Ensure this matches the required Node.js version

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: npm install

      # Step 4: Build client cache (this places the files in the 'caches' folder)
      - name: Build client cache
        run: node build full

      # Step 5: Create a redirect page (index.html that points to testclient.html)
      - name: Create redirect to testclient.html
        run: |
          echo '<!DOCTYPE html>' > ./caches/index.html
          echo '<html>' >> ./caches/index.html
          echo '  <head>' >> ./caches/index.html
          echo '    <meta http-equiv="refresh" content="0; url=testclient.html" />' >> ./caches/index.html
          echo '  </head>' >> ./caches/index.html
          echo '</html>' >> ./caches/index.html

      # Step 6: Deploy to GitHub Pages (files are already in the 'caches' folder)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./caches # Since files are already in the caches folder, use this path directly
